### ISSUE TITLE
Shift right clicking timer picks it up instead of configuring it.

### ISSUE THREAD

**Issue by demethan** [TheLimePixel/GregBlock#10]
I was trying to use  the timer and it is set to 1s as a default. I wanted to make it slower but shift-Right clicking it picks it up and only flash the time config for a fraction of a second. Maybe blacklist the timer from the pickup & go mod?

**Comment by TheLimePixel** [comment]
You could just change the carry key or stay 3 blocks away from it when shift-clicking it.

**Comment by demethan** [comment]
I did try the 3 block away trick.. turns out the clock can`t be configured 3 blocks away. I will change the bind key.. thx
