### ISSUE TITLE
(LV) Power Issue

### ISSUE THREAD

**Issue by RobertLSnead** [TheLimePixel/GregBlock#104]
I'm not sure if it's me or if it's a bug?  I'm having the most difficult time with power on the lv age.
I'm unable to power the blast furnace at all lv only allows 32v and the furnace to smelt aluminum is wanting a whopping 120eu/t and the furnace will not operate at 32v even on a 32amp cobalt with 16 batteries fully charged.  How is that even possible?  I tried checking out videos and they don't have enough power but the furnace processes it any ways granted the video is a two months old.  I'm using 6 steel steam lava boilers to produce a ton of steam and I'm unable to get enough to power the furnace from two lv steam turbines at 32v.   I'm also barely able to power more than 4 machines at the same time also with the lv system.  Not sure how aluminum made it to lv age as the volts are a mv age?
If I can get some help please that would be great.

-Thanks!

Release:
GregBlock-1.4.6
Dec 15, 2018

**Comment by RobertLSnead** [comment]
Going to test 4 32v steam turbines with 16x cobalt and see if that powers the blast furnace.

**Comment by RobertLSnead** [comment]
At two or less I'm getting a warning machine needs more energy.

**Comment by RobertLSnead** [comment]
Well... I did figure this out.
It took 16 steel lava boilers, 4 lv steam turbines, 2.5 lava gens per 4 lava boilers, and three water pumps.
Hope there is a better setup to make the blast furnace work for lv age 2?

Snapshot:
https://pasteboard.co/HUl8kVD.png

**Comment by fluffle** [comment]
FWIW the steel lava boiler produces 20mb/t of steam when fully heated. This is == to 10EU/t of power. 

I'm not sure how much you want advice, so look away now if you don't. Github sadly doesn't come with spoiler tags :-)

You probably want to move to netherrack under your crucibles, I have 18 crucibles powering 64 steel lava boilers. Power is a constant struggle in this pack, scale out then up! I found the 64 lava boilers and a 2x2 of steel multiblock boilers powered by a max size forestry tree farm and a 2x2 of pyrolyse ovens generating charcoal and creosote (2 boilers on each) has just about got me through to HV, just about. This works out at (4880mb/t steam or 2440 EU/t).

**Comment by RobertLSnead** [comment]
I'm not really worried about spoilers, they have been around since the 80's :P 

Anyways thanks for the great tip.  Trying to automate witch water also for raw oil to burn also.
Been following Kharax82 for alot of help through the pack.
