### ISSUE TITLE
Cobalt - Screw Driver

### ISSUE THREAD

**Issue by RobertLSnead** [TheLimePixel/GregBlock#105]
Unable to craft anything with the cobalt screw driver!
To test try making stone gears!

**Comment by RobertLSnead** [comment]
It appears to work or not work when using the work table must be some wierd nbt issue?
Had the same issue with other tools when they near the end of the life of a tool the recipe stops working for some time.

**Comment by mwchase** [comment]
Could this be https://github.com/EmosewaPixel/GregBlock/issues/6?

**Comment by TheLimePixel** [comment]
Yup
