### ISSUE TITLE
Advanced Autoclave doesn't stop crafting carbon fibers when the stack of 64 in the output slot is full

### ISSUE THREAD

**Issue by fluffle** [TheLimePixel/GregBlock#110]
I only noticed this accidentally after it had burned through literally thousands of carbon dust :-(

My setup: MV autoclave underneath MV fluid extractor extracting palladium. AE storage bus on the autoclave, so that when it hits the stack size of 64 the backpressure stops crafting. Only it doesn't!

I wonder if it's because it's a chanced recipe, so even if there's a 100% chance because of overclocking it doesn't stop crafting?

I'll fix it by not keeping a stock, I suppose, but still, ouch.

**Comment by TheLimePixel** [comment]
Yes, GT does that for chanced outputs.
