### ISSUE TITLE
Suggestion about expert mode

### ISSUE THREAD

**Issue by sunnytan53** [TheLimePixel/GregBlock#119]
I know that this pack aims to introduce GregTech to new players who never played through it. But how about adding an expert mode like making the recipes harder or getting the resource in harder or more complexes ways? That can be a good challenge after players finish the “introduction” mode. There is no need to add more mods. Just need another crafttweaker file for the new changes. Does that sound good?

**Comment by TheLimePixel** [comment]
Definitely not.
