### ISSUE TITLE
Squid not spawning.

### ISSUE THREAD

**Issue by Proha5** [TheLimePixel/GregBlock#128]
Bad english.
I build squid farm(16x16). Also, i have pool of water 5x5x5.
I played 2 days. No ONE squid spawned.
I play singleplayer. No additional mod. All settings is default.

Water Y from 45 to 60. No block betwen water and sky. I keef distance >40.
Peace mobs and hostile mobs spawning fine.
Squid Bait spawning fine. Only vanila squid spawn not working.

I know, that end game will requere tons of inculated LV cables. (for superconductor wires using LV electric pump). How mass fabricate black ink?

I found alternate way - use spray can. 1 bottle requere 1 black dye. And i can paint 512 black wools. But this process not automated. I should manualy placed, paint and pickup wools.

**Comment by Zixxl** [comment]
I only have one source block with water running down and squids are spawning fine. As an alternative to squids you can use black dye on sheeps and shear the wool directly from them.

**Comment by Proha5** [comment]
> I only have one source block with water running down and squids are spawning fine. As an alternative to squids you can use black dye on sheeps and shear the wool directly from them.

Yes. Already i shear black sheeps. But i need black dye(not wool) for diodes. Squid still no spawn. I tried plains and swampland biome. Why not spawning?
