### ISSUE TITLE
No Recipe for Prismarine Crystals

### ISSUE THREAD

**Issue by MeniMeniMeni** [TheLimePixel/GregBlock#129]
No recipe for prismarine crystals. This makes crafting sea lanterns impossible.

**Comment by TheLimePixel** [comment]
Did they ever have a recipe?

**Comment by MeniMeniMeni** [comment]
Depends on the modpack.
As far as I know without an added recipe from a mod (via crafting, sieving, etc), it's impossible to get them aside from guardians, or from natural world gen (chest loot and from breaking naturally spawned lanterns). But guardians can only spawn in naturally generated water temples.

Maybe it could be added to the new fisher or along side prismarine in the sieve?

**Comment by TheLimePixel** [comment]
Nah, I'll add a forge hammer recipe.
