### ISSUE TITLE
Machines Stop Working When an Item is in the Output Slot

### ISSUE THREAD

**Issue by MeniMeniMeni** [TheLimePixel/GregBlock#130]
Machines like furnaces and multi blocks, etc. stop working when any item is in their output slot. This is happening in both SP and MP, even with a fresh world/pack install.

https://i.imgur.com/LE2SJwV.png
https://i.imgur.com/ljH7JZp.png

Only some recipes seem to affect single block GT machines.

Multiple members on my server can confirm the same issues.

**Comment by MeniMeniMeni** [comment]
To add on to this, machines with multiple outputs seem to work fine after an item from one output is emptied. For example, the dust in a blast furnace.
After testing some more items, it seems to be inconsistently based on both the items used, and machine used as well. Some items will stop certain machines, while working fine it others, some items will work in both, some will break both.
A couple examples are GT iron ore will work fine in a steam furnace, but will break a vanilla furnace. Where as unfired clay buckets will break both.

Will do some more testing in the morning, hopefully that can help narrow down the root cause.

**Comment by TheLimePixel** [comment]
Tell me if it's fixed in the latest version.

**Comment by MeniMeniMeni** [comment]
Seems fixed. I haven't had any issues with it since the update and neither has anyone on our server from what I've heard.
