### ISSUE TITLE
Separate Gregblock 1 and Gregblock2 ?

### ISSUE THREAD

**Issue by Proha5** [TheLimePixel/GregBlock#132]
(bad english).
GB1 worlds not compatible with GB2.
GB2 have very big differents.
Many players update modpack and lost existing worlds.
I still play GB1. I ignore button "update modpack". I wait update for GB1. But GB1 no have update anymore.
May be separate GB1 and GB2?
And do update for gb1 and gb2 separately?

**Comment by TheLimePixel** [comment]
No. GB1 is done.
