### ISSUE TITLE
Server issues De-sync/crashing

### ISSUE THREAD

**Issue by Icysnowman** [TheLimePixel/GregBlock#133]
on the latest version upgrading our world from version 1.4.6 to the 2.1.0 alot of items changed id (minor problem but overcomable) but i am getting this de-sync of bronze/copper (possibly any pipe) pipe where they will appear for one person but not another when placed and they seem to be throwing alot of errors in the server cmd and crashes the server alot or gives an error where if someone is kicked for playing with them they just get instantly disconnected when trying to rejoin the server (internal server error) even if the pipes are broken and replaced the issue still seems to happen is there a fix for this or is it a problem with the pipes? https://gyazo.com/404805675b9673af0a812232f5e8df08b is a photo of the set up it is connected to. if anymore details are needed just ask

**Comment by TheLimePixel** [comment]
You're not supposed to update old worlds to 2.0.x because of this. Nothing can be done

**Comment by Icysnowman** [comment]
Ok sorry thank you for letting me know. :)
