### ISSUE TITLE
Troubles with wires

### ISSUE THREAD

**Issue by Radorp** [TheLimePixel/GregBlock#134]
1. In the pack things can be painted black just in two ways: bees and squids. Personally I think this is not about fun gameplay, but about grind. So, I suggest to add some alternate black dye recipe (once upon a time Thermal Expansion used coal dust for this).
2. 1x Red Alloy cable is made with black carpet, string, and 1x Red Alloy wire, BUT in the steam macerator 1x Red Alloy cable outputs Small Pile of Red Alloy Dust and Small Pile of RUBBER PULP. Is this an intentional feature?

**Comment by kristu** [comment]
but squid farm is too easy man i get tons of that in the first hour of gameplay, just place a plataform around 45y and back later to get a tons of ink sac.
to me the problem right now is this gregtech fluid pipe are horrible this pack need thermal dynamics pipes for midgame and late game automation.

**Comment by Radorp** [comment]
> 
> 
> but squid farm is too easy man i get tons of that in the first hour of gameplay, just place a plataform around 45y and back later to get a tons of ink sac.
> to me the problem right now is this gregtech fluid pipe are horrible this pack need thermal dynamics pipes for midgame and late game automation.

The main problem is about wire rubber pulp thing. I do not have that much problem with inc sac.
