### ISSUE TITLE
Sort control for Gregchests malfunctions; overlaps in UI

### ISSUE THREAD

**Issue by jnaset** [TheLimePixel/GregBlock#138]
The buttons to sort the contents of GTCE chests malfunction and scatter the items across the chest slots in a repeatable but incorrect pattern.

Additionally, the buttons to sort the contents of the GTCE chest overlap the inventory slots in the chest, making it difficult to select either the sort button without an item, or an item without triggering the sort.

**Comment by TheLimePixel** [comment]
As mentioned in the changelog, those were temporary, only for that version.
