### ISSUE TITLE
No way to move a GTCE chest with contents

### ISSUE THREAD

**Issue by jnaset** [TheLimePixel/GregBlock#139]
GTCE does not have compatibility with Carry On, nor an alternative means to move one of its large chests while keeping inventory.  GTCE should support Carry On, or provide an item like a dolly to move the chests around.  Alternatively, a mod could be added with an item like the sack of holding or cardboard box, to move tile entities around.

**Comment by TheLimePixel** [comment]
GTCE tile entities are blacklisted as moving them causes crashes upon interaction with them. So no, you will never be able to move them.
