### ISSUE TITLE
Breaking GTCE machines, tanks, and chests with a TiCon tool is extremely slow

### ISSUE THREAD

**Issue by jnaset** [TheLimePixel/GregBlock#140]
Breaking a GTCE machine, tank, or chest using a Tinker's Construct tool is extremely slow.  Using an otherwise less powerful GTCE pick breaks the blocks much much faster.  There seems to be a compatibility issue between GTCE and TiCon where the stats on the TiCon pick are not used correctly when calculating how long breaking a block should take.

**Comment by kristu** [comment]
it's that before tinkers too and in GT New Horizons too, just use wrench is instant for any GT machine or multiblock
