### ISSUE TITLE
Suggestion: Allow fluid containers to satisfy rock breaker requirements

### ISSUE THREAD

**Issue by jnaset** [TheLimePixel/GregBlock#142]
Since the stone breaker has to be placed fairly close to other machinery in early/mid game due to power loss over distance, it would be convenient if the water and lava blocks could be containers with >=1 bucket of lava and water.  Alternatively, the rock breaker could have fluid tanks to hold the lava and water.

Currently, having a steam/power input, item output, redstone input, and two sides being fluid blocks (using 5 of the 6 sides), it's a difficult machine to work with.

**Comment by Dekrasias** [comment]
Hi, just a random. I've been having issues getting the stone breaker working and can't find anything online. Could you possibly show my your setup/explain how to get it working? I'm really stuck here because I also don't have the simple cobblestone generator.

**Comment by jnaset** [comment]
@Dekrasias: The rock breaker is much like any other steam machine, except: it has no steam vent, and the side indicated with a square is the side to which it will eject the blocks it creates.  The other special feature of the rock breaker is that it must be horizontally adjacent to a water source block and a lava source block.  It will create cobble, unless you supply a redstone signal, in which case it will produce cobble, granite, andesite, or diorite depending on the signal strength.

**Comment by DonavanGaudet** [comment]
hey, seeing as the update gives me NO information on anything, whats a good way to chance the signal strength of redstone? they removed all the vanilla redstone doodads and I dont want to run a long ass line of redstone just to get andesite or granite. So if by chance you or anyone knows how to do that i'd love to know.

**Comment by jnaset** [comment]
I've been using a ProjectRed comparator exactly like I would otherwise use a vanilla comparator for this situation.  If you don't have the materials to build a comparator (or other ProjectRed parts) I think you might be stuck with a long redstone line...

**Comment by TheLimePixel** [comment]
No, I'm not doing that. It's supposed to not be a compact machine.
