### ISSUE TITLE
Project red not transporting

### ISSUE THREAD

**Issue by mokniker** [TheLimePixel/GregBlock#144]
My drawers are incapable of accepting input from project red pipes. I also can't use them to extract from machines. I tried using pressurized and routing pipes in my test world and neither one can move items where I wan't them.

**Comment by TheLimePixel** [comment]
While that does seem to be case for Pressure Pipes that I'm not sure whether or not it's an intended limitation or bug (the mod hasn't been updated in months anyways), routing pipes work just fine. I'm assuming you didn't set your Responder Chips to blacklist.
