### ISSUE TITLE
Simple Cobblestone Generator Uncraftable

### ISSUE THREAD

**Issue by Dekrasias** [TheLimePixel/GregBlock#145]
Have been watching videos and saw that there is a simple cobblestone generator. But the recipe is not in JEI and when I put in the recipe it does not bring anything back. So I skipped to the steam rock breaker and I can''t seem to get that to work either!

**Comment by kristu** [comment]
mod removed in 2.0.0 version look the changelog.
it's easy make a cobblestone, diorite, granite and andersite natural generator just need a little more work

**Comment by Dekrasias** [comment]
Do you mean with mining it like a normal cobble stone generator? Because I have done so but I've gotten to making steam engine age and would like to get my stuff automated. I thought I wouldn't need the simple generator if I could make the steam rock breaker but now I can't even find out how to get the steam rock breaker to work. I am on version 2.2.0 so that explains not having the simple generator. @kristu

**Comment by kristu** [comment]
@Dekrasias
yes u can make diorite granite and andersite like a cobblestone generator, u just need added more range to water flow i do no if u will understand but it's a bit simple 1 range water cobblestone, 2 range flow water diorite, and just add more flow two in two if u cannot understand i can make a pic from my save and i use auto breaker with redstone timer to automate.

Edit. https://imgur.com/HGv58J9
just for info, u cant make breakers and timers until LV age, but u can rush a little to get that and u can alterate the design added more rows like before i used 5 row of each just be careful to not veinminer u entire plataform like me lol
btw i know this plataform is horrible i just cover the top with halfslab and make my base some chunks away lolllll i'm lazzy

**Comment by Dekrasias** [comment]
@kristu Thank you. I do currently have a cobble, granite, and diorite generator setup that I put a weight on my mouse at to afk mine ;) But I really am tired of doing that and wish to automate sooner. I'm sure I'll to that stage soon but I would like to get the steam rock breaker going. Did you ever experiment with it? I appreciate the reply.

**Comment by kristu** [comment]
@Dekrasias maybe in future when i automate the sieves, but i stop my save right now because gt fluid pipes are so annoying the automation is a fucking mess to deal with differents fluids, extraction, insert, fluid storage, so i will put my save on hold maybe i back in the future but i'm tired of that
