### ISSUE TITLE
Suggestion: Add a way to automate decorative GTCE blocks (marble, basalt, red/black granite)

### ISSUE THREAD

**Issue by jnaset** [TheLimePixel/GregBlock#146]
The decorative GTCE blocks: marble, basalt, black and red granite, are craftable from pebbles; however the pebbles are not obtainable with the GT sieving machines, only the by-hand sieve.  There are also some sands/dusts related to these blocks that can be created with GT that have no other specific purpose but could plausibly be turned back into the decorative blocks somehow.

Also the vanilla MC quartz block (and its other variants craftable from it) do not seem to have a recipe.

**Comment by TheLimePixel** [comment]
There really isn't any possible way that'd make sense and be consistent and since they aren't really needed in progress I haven't and won't add a way of automating them. I have however fixed the second issue.
