### ISSUE TITLE
Unbuildable Primitive Blast Furnace 2.2.0

### ISSUE THREAD

**Issue by Alfawar** [TheLimePixel/GregBlock#150]
It is impossible to build Primitive Blast Furnace because there is no recipe for Concrete Bucket in JEI.

**Comment by LAGIdiot** [comment]
Just because bucket recipe is not registered (as for nearly everything) it does not mean you can't created it. Just use (steam) mixer Concrete and then click output slot with bucket. And voila you have Concrete Bucket.
