### ISSUE TITLE
Minor: Move Quartz Fiber crafting to Autoclave

### ISSUE THREAD

**Issue by Vyraal1** [TheLimePixel/GregBlock#16]
Thematically Autoclave deals with enriching dusts back to crystals, figured it might thematically fit better than in the assembler + liquid glass.
![image](https://user-images.githubusercontent.com/26587049/46414237-ace5eb80-c6f0-11e8-9cab-66e3082e5155.png)

**Comment by TheLimePixel** [comment]
And seeing that the Autoclave otherwise wouldn't be used much, that is indeed a good idea
