### ISSUE TITLE
Simple Cobblestone Generator Uncraftable

### ISSUE THREAD

**Issue by Kinsata** [TheLimePixel/GregBlock#17]
I don't know which patch did it, but tried to create a second cobblegen today, and the recipe shift clicks from JEI (4 cobble, water bucket, lava bucket, 2 iron picks, and a wrench) and there is nothing in the output slot. 

https://i.imgur.com/YxrS6a5.png

**Comment by Mokradin** [comment]
I have the same issue, the pack version is 1.1.2

![2018-10-05_12 57 43](https://user-images.githubusercontent.com/2047404/46531669-55857e00-c89e-11e8-88a9-78e02c72bbb3.png)

**Comment by TheLimePixel** [comment]
Woops

**Comment by Grobes** [comment]
This is also affecting other crafts requiring GT tools such as the Plant Interactor from IF
