### ISSUE TITLE
Diamond rods not craftable

### ISSUE THREAD

**Issue by XyCrosier** [TheLimePixel/GregBlock#174]
I see issues #141 and #148 were also about a few varieties of gem-based rod recipes that were missing. Uncertain on how comprehensive the fix on those was (did ALL gems get rod recipes?), I'm trying to make sure diamond rods also get fixed in the next update, as these have not been specifically mentioned yet.

In the current release version (2.2.0) they are not craftable.

They are required for diamond gears (which is a component of both the splicer and inoculator)
They are required for diamantine electron tubes (which are components of a few alveary blocks.)
They are required for advanced ME cards.

**Comment by jnaset** [comment]
This was fixed in 2.2.1.

**Comment by XyCrosier** [comment]
Thank you. I hadn't noticed 2.2.1 was available for testing. For some reason I had it in my brain that the next version was in private development.
