### ISSUE TITLE
Few Issues (On 1.1.2

### ISSUE THREAD

**Issue by Grobes** [TheLimePixel/GregBlock#18]
- [ ] 4 Diamond spikes craft directly from a diamond block (likely as gemstone blades were removed)

 - [x] The Ender Pearl Dust required for the ME Controller quest is not craftable, only the GT version is. The Singularities are craftable with the GT dust.

 - [x] The Ethylene quest requires 144mB of Ethylene for completion, same as the soldering alloy one did. Needs to be changed to 1000mb.

Great pack. Thanks for the work.

**Comment by TheLimePixel** [comment]
The former will be fixed in the next minor update (this weekend when GT updates)
