### ISSUE TITLE
Minor: Remove Nichrome Dust from Nichrome Quest

### ISSUE THREAD

**Issue by Vyraal1** [TheLimePixel/GregBlock#20]
Nichrome can either be made via the Dust or just alloying Nickel/Chrome in the EBF. Even though the latter is a higher voltage tier, its faster and more efficient (outputs 5 at a time) to just use the second recipe, especially if players store everything as ingots. So aside from being optional, it's also inefficient.
![image](https://user-images.githubusercontent.com/26587049/46550361-d34b8880-c8a2-11e8-8e02-031671d60649.png)

**Comment by TheLimePixel** [comment]
Huh, I did not see that...
