### ISSUE TITLE
cant get glass in version 2.2.0

### ISSUE THREAD

**Issue by kzero12357** [TheLimePixel/GregBlock#205]
when you try to get class out of the smeltery it does not work. also sand will not smelt in a furnace

**Comment by kzero12357** [comment]
update the Gregsconstruct mod is not generating a config and i think this may be causing an issue

**Comment by Houndie** [comment]
I'm playing GB 2.2.0 and glass works fine to me?

Melt sand in smeltery, use a casting basin to get glass blocks, or a casting table for glass panes both work for me.

**Comment by kzero12357** [comment]
Final update. Restarted client and server and it seems to work now. Must have been a glitch or memory leakage! Thank you!

**Comment by martcor** [comment]
Restarting server worked for me too. But surely did not work before restarting.
