### ISSUE TITLE
Cable Anchors Uncraftable After Damaging Knife Once

### ISSUE THREAD

**Issue by Vyraal1** [TheLimePixel/GregBlock#21]
Cable Anchors from applied energistics can only be crafted with a full certus quartz cutting knife.

![image](https://user-images.githubusercontent.com/26587049/46564002-bdee5280-c8d2-11e8-8346-19b653748169.png)

Have tried the recipe with both vanilla iron ingots and GregTech ingots.
![image](https://user-images.githubusercontent.com/26587049/46564020-dbbbb780-c8d2-11e8-8024-1d3480da9bb1.png)

**Comment by TheLimePixel** [comment]
:thinking: So why are you reporting this issue to me when I obviously have nothing to do with it?

**Comment by TheLimePixel** [comment]
Huh, it seems to be fixed in the next AE2 version.
