### ISSUE TITLE
Missing text on Age 1 steel quest #29

### ISSUE THREAD

**Issue by PlacidK** [TheLimePixel/GregBlock#22]
Version 1.1.3

Added optifine (if that matters)

There is no text in the quest description.
I know because a get an error when i look at that quest.

[main/ERROR] [betterquesting]: LINE COUNT MISSMATCH (5 != 6) ON TEXT:  In order to progress to tier 3 resources, you are going to need Steel, which is made from Iron and Coal, Charcoal or Coal Coke in a Primitive Blast Furnace. To make one, you are in theory just going to need a lot of Clay, 144 to be exact. You are first going to need to turn Bricks into Brick Dust and Clay into Clay Dust, combine them to make Fireclay Dust, compress it, smelt it and then craft 4 of the Bricks you made into Primitive Bricks.

**Comment by TheLimePixel** [comment]
Yeah, it's been a while... I'm going to assume the issue was related to OptiFine.
