### ISSUE TITLE
Crash bug with drum and vanilla redstone powder

### ISSUE THREAD

**Issue by KatatsumuriPan** [TheLimePixel/GregBlock#229]
I found a crashing bug in version 2.2.1.
Place a drum, a redstone powder, and a block as in the picture then it will crash.
(Replace the orange wool with any metal drum)

**Comment by KatatsumuriPan** [comment]
![GregBlock _Crash_Bug](https://user-images.githubusercontent.com/79035439/107869657-ceb42780-6ed3-11eb-96d2-f97d71b49f96.png)

**Comment by CrafterKolyan** [comment]
Maybe it's bug from GregTechCE. In the Revamped version this crash is fixed https://github.com/programgames/Gregblock-revamped/releases .

**Comment by KatatsumuriPan** [comment]
Thanks a lot.
