### ISSUE TITLE
Forestry electric machine quests available before any source of RF

### ISSUE THREAD

**Issue by Catonyx** [TheLimePixel/GregBlock#24]
The forestry machine quests open up as soon as LV begins. But GTCE cables don't support outputting FE so the earliest RF generation is either the Forestry engines (lapis plates) or the IF petrified fuel generator (polyethylene)

**Comment by TheLimePixel** [comment]
Oh, that was fixed in the last version.

**Comment by Catonyx** [comment]
Is there a way to reload the quest book? I can't verify that it was fixed on my end
