### ISSUE TITLE
Radon Production Infinite Loop?

### ISSUE THREAD

**Issue by Vyraal1** [TheLimePixel/GregBlock#25]
![image](https://user-images.githubusercontent.com/26587049/46636228-4b28e580-cb25-11e8-9ef1-6b8a98bbb0e0.png)

![image](https://user-images.githubusercontent.com/26587049/46636235-51b75d00-cb25-11e8-963a-e4adfcef886d.png)

![image](https://user-images.githubusercontent.com/26587049/46636248-58de6b00-cb25-11e8-8923-b35829b3f9cd.png)

Seems to be a repetitive loop for Radon, granted this does take a LONG time for a time gate, and Plutonium-244 is a pain to get as well, but was wondering if this was intentional.

**Comment by TheLimePixel** [comment]
Yup, that's how it was in GT5U.
