### ISSUE TITLE
Multismelter console spam

### ISSUE THREAD

**Issue by thaimichael** [TheLimePixel/GregBlock#29]
Have 1 multismelter setup on the test server with MV Input/Output hatch Nicome coils and HV Energy Input with no console spam.  
Vyraal's server is similar but the Input/Output hatch is HV and in a Quad setup.  While formed the console is being constantly spammed with a recipe error log sample attached.
https://pastebin.com/wrXJBJXD

**Comment by Vyraal1** [comment]
The console is pretty much unusuable with this spam, even when the multismelter is off and has nothing being processed I seem to be getting this error.
