### ISSUE TITLE
Steam Compressor Makes Chiseled Iron Blocks

### ISSUE THREAD

**Issue by Vyraal1** [TheLimePixel/GregBlock#3]
![2018-09-27_09 22 39](https://user-images.githubusercontent.com/26587049/46148884-0d7bb100-c237-11e8-9cdd-d09a7f6a7dde.png)

Pack Version: 1.0.1

**Comment by TheLimePixel** [comment]
I actually managed to fix it. :D

**Comment by AnthonyPorthouse** [comment]
Hopefully this also corrects the inconsistency where the Steam compressor was making chiseled Redstone blocks too.
