### ISSUE TITLE
Simple Cobblestone Generator doesn´t work

### ISSUE THREAD

**Issue by mitgehangen** [TheLimePixel/GregBlock#32]
I can´t craft a simple cobblesone generator. I tried to get it in creative mode, but this item doesn´t exist (neither in survival nor in creativ). Its impossible to craft this generator

**Comment by TheLimePixel** [comment]
You use an Iron Pickaxe to craft it.

**Comment by Dekrasias** [comment]
I can not create the simple cobblestone generator either. Don't have the quest for it. Am using iron pickaxe's both brand new, Have not tried creative yet. But it's also not in JEI.
