### ISSUE TITLE
Quest for conveyors?

### ISSUE THREAD

**Issue by Catonyx** [TheLimePixel/GregBlock#34]
I have built conveyors and haven't seen any quests for them, even as an unavailable quest. If they exist, what unlocks them?

**Comment by TheLimePixel** [comment]
You just need to have the Plastic Age unlocked.

**Comment by Catonyx** [comment]
Isn't that an issue though? You can get conveyors long before the Plastic age using sticky resin, in almost exactly the same way that you would in GT5
