### ISSUE TITLE
Transformer reset after server restart

### ISSUE THREAD

**Issue by krakel** [TheLimePixel/GregBlock#36]
You can change the transformer behavior with a RubberSoftHammer from down to up. After a server restart the transformer forget it and will burn all cable connectet at the output.

nice to have: the tooltip of the transformer should show the transforming direction

**Comment by TheLimePixel** [comment]
Or, I guess I shouldn't have closed it. I'm just frustrated that hey closed my issue. Sorry
https://github.com/GregTechCE/GregTech/issues/381
