### ISSUE TITLE
ME Drive Recipe Ore Dictionary Circuit $circuitGAElite

### ISSUE THREAD

**Issue by Vyraal1** [TheLimePixel/GregBlock#39]
![image](https://user-images.githubusercontent.com/26587049/46967260-07326500-d07e-11e8-9eb9-2f220e5650c2.png)

Only uses the quantum processor assembly, should also allow for other ore dictionaried elite circuits.

**Comment by TheLimePixel** [comment]
Nope, I specifically made it require that circuit.
