### ISSUE TITLE
Zip for gnu/linux users, or at least a note on wich forge to use

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [TheLimePixel/GregBlock#40]
Hi!
As you might not know twitch/curse launcher doesn't work for GNU/linux platforms, so I use cmpdl to download the pack but have to download the metadata/manifest zip file and check what forge version you're running.

Could you provide/note in the description the forge version? It's a quality of life improvement.

Thank you for your time.

**Comment by TheLimePixel** [comment]
It's version 14.23.5.2768
 I tend to stick to a version until something becomes incompatible. I guess I'll mention it the next time I change it.
