### ISSUE TITLE
Tin Alloy Ingot Production

### ISSUE THREAD

**Issue by g3r4xd3on** [TheLimePixel/GregBlock#41]
I can't produce Tin Alloy Ingot (SnFe) on Steam Alloy Smelter. And I guess there is no other recipe on NEI. But I need SnFe to produce Tin Alloy Mesh and to jump Tier 2 sifting. Why even didnt write on guide book how to do this ? Please add more information on guide book like this.

**Comment by TheLimePixel** [comment]
I have no idea what you're talking about
![image](https://user-images.githubusercontent.com/25333164/47187992-7a660080-d336-11e8-98fa-4793d022dc40.png)

**Comment by g3r4xd3on** [comment]
Okay I saw your picture but it did'nt work on me. I guess it's because of Turkish Language. I will try to change windows language to english. Than maybe it will work. Thanks about answer.
