### ISSUE TITLE
Age 2 "Waffles" Quest

### ISSUE THREAD

**Issue by Stephfra** [TheLimePixel/GregBlock#44]
The Quest "Waffels" in Age 2 may should be moved to Age 3.
This Quest require the player to optain Silicion, but Silicon cant be optained without haveing an MV Electrolyser.

**Comment by syrun97** [comment]
you can make silicon in LV age with blast furnace.
![2018-10-25_14 36 53](https://user-images.githubusercontent.com/19798397/47478183-a49e4d80-d863-11e8-9ac6-bd52b49c80fc.png)
![2018-10-25_14 36 59](https://user-images.githubusercontent.com/19798397/47478185-a49e4d80-d863-11e8-8684-81ecb97148cd.png)
