### ISSUE TITLE
Age 3 Quest - "Ethanol"

### ISSUE THREAD

**Issue by Stephfra** [TheLimePixel/GregBlock#45]
This Quest should need "Any" Brewery, not Advanced Brewery.
You can optain Biomass with an LV Brewery and there is no need for an Advanced Brewery in this Quest.

**Comment by TheLimePixel** [comment]
The LV one is too slow. Stop nitpicking.

**Comment by Stephfra** [comment]
This is a genuine problem as a Normal player i wouldnt see the "Ethanol" Quest and All the Quests after that, without building an Advanced Brewery, also as a normal player i would never had the idea to build an MV Brewery, because all recepies only need 3 eu/t. This Quest realy blocks progression.
