### ISSUE TITLE
Add in Superconductor Cable Recipe?

### ISSUE THREAD

**Issue by Vyraal1** [TheLimePixel/GregBlock#47]
There are superconductor cables added by GT but they don't have a recipe, it would be nice to stop constantly dying. 

![image](https://user-images.githubusercontent.com/26587049/47269592-43f2d600-d52e-11e8-93aa-ab7132e0d050.png)

**Comment by ThatGravyBoat** [comment]
since vyraal wont post his song i will. 
![image](https://user-images.githubusercontent.com/26934102/47269623-342dbe80-d53b-11e8-8862-e8957b24d884.png)

**Comment by TheLimePixel** [comment]
No
