### ISSUE TITLE
Does this recipe is automate-able?

### ISSUE THREAD

**Issue by syrun97** [TheLimePixel/GregBlock#50]
![2018-10-25_14 24 40](https://user-images.githubusercontent.com/19798397/47478492-6ead9900-d864-11e8-865f-6ff3dba57c34.png)
That recipe need 1 energy side, 3 fluid input, 1 item input and output, and 2 fluid output.
But there's only 6 sides on block. ;(

**Comment by TheLimePixel** [comment]
You'll be able to automate it when you get an ME system.
