### ISSUE TITLE
Clear / Opaque Item Ducts Recipies

### ISSUE THREAD

**Issue by cadyb** [TheLimePixel/GregBlock#51]
Could a recipe tweak to make Opaque Item Ducts cheaper or Clear ones more expensive be possible? I'm not sure if they do anymore but in the past the Clear kind caused server lag and they cause weaker clients to have fps lag.

I noticed in the 1.2.0 change log the recipe for regular hardened glass was changed to be gated behind lead but you can still craft item ducts with any kind of hardened glass including tin which in my play through we had an abundance of making it the clear choice.

**Comment by TheLimePixel** [comment]
No
