### ISSUE TITLE
Carry on Blacklist

### ISSUE THREAD

**Issue by cadyb** [TheLimePixel/GregBlock#52]
The Carry on Blacklist could use some additions.
ExNihilo sieves are picked up when you try to remove the meshes
Redstone Logic Gates from Charset are edited by shift clicking with a right hand so they also get picked up. (Charset seems to only add these blocks so you might be able to get away with just blacklisting the whole mod in the carry on config)

**Comment by TheLimePixel** [comment]
Thanks for reminding me about the sieves.
