### ISSUE TITLE
Certus Quartz 

### ISSUE THREAD

**Issue by cadyb** [TheLimePixel/GregBlock#53]
GT Certus Quartz Dust cant be autoclaved into AE Certus Quartz or even GT Certus Quartz.
GT Certus Quartz isnt used for any AE recipes.

**Comment by TheLimePixel** [comment]
I have no idea what you're talking about
![image](https://user-images.githubusercontent.com/25333164/47744976-e293db00-dc82-11e8-8c29-1ebcb2839766.png)

**Comment by cadyb** [comment]
The Gregtech Certus Quartz dust not the AE Certus Quartz Dust
[Jei Uses for GT Certuz Quartz Dust](https://i.imgur.com/UgF01Xx.png)
[Jei Uses for GT Certuz Quartz Dust](https://i.imgur.com/ztV8Ir0.png)

This makes it so you cant process Fine Certus Quartz Ore chunks with a Macerator if you want to be able to use them for AE since you get the Gregtech Dusts which are useless and cannot be autoclaved
