### ISSUE TITLE
[SUGGESTION] Following removal of vanilla hoppers, how about a (repeatable) quest to turn in 1 vanilla hopper and receive 1 Pneumaticraft hopper?

### ISSUE THREAD

**Issue by dmsaxon** [TheLimePixel/GregBlock#55]
I appreciate iron is relatively easy to come by, but this would be a nice way to upgrade existing automation systems following the change in 1.3.0a

**Comment by TheLimePixel** [comment]
But iron is so common and it's not like your existing hoppers are unusable. :man_shrugging: No.
