### ISSUE TITLE
PneumaticCraft hoppers (1.3.1) usually fail to extract from machines

### ISSUE THREAD

**Issue by CrossElectronics** [TheLimePixel/GregBlock#58]
**Version** 1.3.1 
**Forge** 14.23.5.2768
**Source** Curseforge
**Rarity** Quite common (for me)

**Description**
After updating the pack, I noticed that the vanilla hoppers are replaced by PneumaticCraft hoppers. The new hoppers, however, appear to _halt_ the extraction process every few minutes even though the hoppers are empty (fig 1&2). The same issue appeared on the high pressure furnace when I tried to automate it as well. It is stopping players from doing basic automations.

**Trigger Condition**
Uncertain, maybe a full hopper slot can trigger the bug?

**Temporary Solution**
To re-enable the hoppers, I have to take out everything from the machine's INPUT slot before it gets stuck a few minutes later again (fig. 3)(clearing output slot not working, only clearing the input slot works). 

**Information Related**
Tried changing extracting sides, no effect.
The vanilla hoppers don't appear to have this kind of issue.
Extraction from the chest seems okay.

![1](https://user-images.githubusercontent.com/31400327/47916560-88dd1c00-dee1-11e8-80fe-cf614521a29c.png)
![2](https://user-images.githubusercontent.com/31400327/47916565-8e3a6680-dee1-11e8-8372-6e69d57570b8.png)
![3](https://user-images.githubusercontent.com/31400327/47916573-90042a00-dee1-11e8-83ff-c7eca4007a18.png)

**Comment by SummitSummit** [comment]
Hey!  Glad it's not just me.  Thought I was going insane for a bit there.
