### ISSUE TITLE
Simple Cobblestone Generator recipe(?) fault

### ISSUE THREAD

**Issue by MrSteggo** [TheLimePixel/GregBlock#59]
Using the JEI autofill and manually filling the table both refuse to craft.

[What I'm looking at](https://i.gyazo.com/c533fc6d53a9c52705c7f02102ad0e47.png)

**Comment by MrSteggo** [comment]
Patch fixed it <3

**Comment by mytholibar** [comment]
V1.4.1 not working quite yet.
![1](https://user-images.githubusercontent.com/12012547/48676537-ffeaf500-eb1c-11e8-9633-9842eaf4ec6a.png)

**Comment by Dekrasias** [comment]
I can't create it with V2.2.0 on the twitch launcher.
