### ISSUE TITLE
Diamond Hammer Incompatible with Itemduct Recipe

### ISSUE THREAD

**Issue by Vyraal1** [TheLimePixel/GregBlock#6]
![image](https://user-images.githubusercontent.com/26587049/46238454-4c565780-c35a-11e8-8566-3704f1676158.png)

![image](https://user-images.githubusercontent.com/26587049/46238506-a3f4c300-c35a-11e8-8260-2f5c08a0003e.png)
Not sure what's the cause of this, this is the `/ct hand` output of the Diamond Hammer in hand, seems to work for double ingot recipes.

In comparison, Steel hammer works just fine.
![image](https://user-images.githubusercontent.com/26587049/46238516-bd960a80-c35a-11e8-92de-61c9f57f500d.png)

This is the `/ct hand` output of steel hammer:
```
<gregtech:meta_tool:6>.withTag(
	{
		ench: [
			{
				lvl: 2 as short, 
				id: 16 as short
			}
			], 
		RandomKey: 7821170268237448292 as long, 
		CreatorMost: -2161625569645476431 as long, 
		CraftingComponents: [
			{
				id: "gregtech:meta_item_1", 
				Count: 1 as byte, 
				Damage: 10184 as short
			}, 
			{
				id: "gregtech:meta_item_1", 
				Count: 1 as byte, 
				Damage: 10184 as short
			}, 
			{
				id: "gregtech:meta_item_1", 
				Count: 1 as byte, 
				Damage: 10184 as short
			}, 
			{
				id: "gregtech:meta_item_1", 
				Count: 1 as byte, 
				Damage: 10184 as short
			}, 
			{
				id: "minecraft:stick", 
				Count: 1 as byte, 
				Damage: 0 as short
			}, 
			{
				id: "gregtech:meta_item_1", 
				Count: 1 as byte, 
				Damage: 10184 as short
			}, 
			{
				id: "gregtech:meta_item_1", 
				Count: 1 as byte, 
				Damage: 10184 as short
			}
		], 
		"GT.ToolStats": {PrimaryMaterial: "steel", HandleMaterial: "wood", Damage: 40}, CreatorLeast: -5978481493637691621 as long})
```

**Comment by Numorphan** [comment]
Just noticed something for this: It looks like the recipe doesn't like certain tools that have less then 100% durability. If you cheat in a Darmstadtium Hammer, for example, you'll find that it works for exactly one craft. Same with a Manganese or Darmstadtium Bending Cylinder, you'll find the same issue.
