### ISSUE TITLE
Edit: Lava Boiler not accepting lava after accident

### ISSUE THREAD

**Issue by Shanarei** [TheLimePixel/GregBlock#61]
![image](https://user-images.githubusercontent.com/44799395/48050773-3468c380-e1a3-11e8-9d74-39163f5dec7b.png)
![image](https://user-images.githubusercontent.com/44799395/48050810-5e21ea80-e1a3-11e8-949d-a42a02178102.png)
![image](https://user-images.githubusercontent.com/44799395/48050816-6d089d00-e1a3-11e8-9d8a-e3f82409af83.png)
Dunno if the images explain it - i have a lava production, lava is pulled out by liquid hopper - the moment i connect the hardened fluidduct the lava starts draining rapidly but it doesn't go anywhere, it just disappears

**Comment by Shanarei** [comment]
forgot to mention: already have destroyed and rebuilt the pipes several times to make sure they are empty

**Comment by Shanarei** [comment]
Ok i found the issue - the lava boilers don't accept lava anymore - happend after an accident where the lava ducts where connected with wood water pipes, since then they don't accept lava anymore
Destroying and rebuilding the boiler doesn't help
Greg pipes and liquid hopper directly into the boiler doesn't help either

**Comment by TheLimePixel** [comment]
Are the pipes full of steam?

**Comment by Shanarei** [comment]
No, when i connect them to a tank the lava is put in the tank. Like i said, the boiler doesn't accept lava anymore - not even from a bucket put into the input slot of the Boiler.
Somehow the boiler bugged out when the water pipe (made of wood) touched the lava pipe. The wood pipe went up in flames and since then the boiler doesn't take lava anymore - i'll try to reproduce the bug when i have time but i'm not at home right now

**Comment by Shanarei** [comment]
Ok, i'm dumb - was so stressed out about the lava "disappearing" that i didn't test the obvious - the lava boiler doesn't accept lava if it doesn't have water

**Comment by TheLimePixel** [comment]
Oh, yeah, it's made like that so you don't automatically blow it up.
