### ISSUE TITLE
Quest book issues on 1.4.0

### ISSUE THREAD

**Issue by lglare** [TheLimePixel/GregBlock#65]
I reach to age10.
but doesn't craft few machines with need quest to next age.(gate icon)
e.g. IV atmosphere collector,HV extruder,UV field generator and UV emitter.

**Comment by TheLimePixel** [comment]
Some quests require any air collector, which is why the IV Atmosphere Collector is a main quest
I have no idea why the HV Extruder is a main quest
The UV Emitter is needed for the Ultimate Battery, UV Replicator and UV Mass Fabricator, which are other end-game goals.
