### ISSUE TITLE
Network bandwidth was run out by Players Increase

### ISSUE THREAD

**Issue by laazy** [TheLimePixel/GregBlock#69]
Hi, I made a GergBlock server, but I fount that server's upload bandwidth increased very fast. 
When there is one player, the upload is 200+ kb/s, 2 is 700+kb/s, 3 is 1+mb/s, 4 is 3+mb/s, 5 is 4+mb/s.
 I haven't test what will happen when there are more than 5 players.

**Comment by TheLimePixel** [comment]
So what do you expect me to do with only that information? :thinking:

**Comment by laazy** [comment]
I'm using 1.4.0 server pack, And didn't add any other mods. The server is running on ubuntu 18.04 with intel i9 9th cpu and 32g ddr4.

**Comment by TheLimePixel** [comment]
I'm saying that we don't know what's causing it, so there's not really much that can be done.

**Comment by XiaoXuan458** [comment]
The server has no problem in 1.2, but in the version above 1.3

**Comment by TheLimePixel** [comment]
This is most likely related to https://github.com/Funwayguy/BetterQuesting/issues/488
