### ISSUE TITLE
Minor annoyance: Volume on the intro music

### ISSUE THREAD

**Issue by demethan** [TheLimePixel/GregBlock#7]
Would it be possible to turn down the volume on the intro music, to match the volume of all the other soundtracks. 

Love the pack btw.  thank you for it.

**Comment by TheLimePixel** [comment]
It's already at 10% by default.

**Comment by demethan** [comment]
ok.. didn't work for me. it was at 100%

**Comment by demethan** [comment]
what I meant is to load the audio file in Audacity and turning down the volume on that actual file. So if MC doesn't keep your music settings, it won't break anyone's ears.
