### ISSUE TITLE
Compressed iron naming issue

### ISSUE THREAD

**Issue by Arsonal** [TheLimePixel/GregBlock#71]
**Version**
1.4.0

**Issue**
compressed iron not using localized names

**screenshots**
![2018-11-14_15 10 04](https://user-images.githubusercontent.com/692402/48513369-3ecd3200-e821-11e8-9fb6-6665d0745bb9.png)
![2018-11-14_15 10 06](https://user-images.githubusercontent.com/692402/48513376-41c82280-e821-11e8-962b-203bcc37acc5.png)

**Comment by TheLimePixel** [comment]
Which OS are you using?

**Comment by Arsonal** [comment]
Arch Linux
