### ISSUE TITLE
LV Quest Chain [Chemical Reactor] + [Fluid Solidifier] + [Sifting Netherrack] -> [Conveyor Module] -> [Assembling Machine]

### ISSUE THREAD

**Issue by marcmagus** [TheLimePixel/GregBlock#73]
Unless I missed something in JEI, there's a fairly hidden dependency in the quest chain leading to the Basic Assembling Machine.

Basic Assembling Machine requires Conveyor Modules, which need Rubber Sheets.

Rubber Sheets can only be made from Rubber Fluid in a Fluid Solidifier.

Rubber Fluid requires Rubber Pulp and Sulfur Dust in a Chemical Reactor.

I suggest adding a quest to Age 2:

[LV Conveyor Module] which should be required for [Basic Assembling Machine] and depend on [Basic Chemical Reactor], [Basic Fluid Solidifier], and [Sifting Netherrack]. You can't get to Age 2 without knowing how to get your Rubber (solid), so that dependency can be implicit.

How many of the steps should be included in the quest, and whether an additional [Liquid Rubber] quest is a better way to capture the information, I leave to the designer, but the current dependency graph is inaccurate and misleading.

**Comment by TheLimePixel** [comment]
Generally, I expect people to either simply follow all the main quests or find it through JEI. I'm not changing this.

**Comment by TheLimePixel** [comment]
On second though, I'm changing it so you don't need the Fluid Solidifier for the Rubber quest, but for the Conveyor Module quest.
