### ISSUE TITLE
Machines Don't Accept Left Click Fluid From Tanks

### ISSUE THREAD

**Issue by Numorphan** [TheLimePixel/GregBlock#80]
Modpack Version: 1.4.2
Client/Server: Server

Many machines have a slot saying something like "Click with a filled container to empty into tank." Buckets work for this, as you'd expect, but if I have say a Bronze Tank full of water, I can't click it in the same way in spite of it being a filled container.

**Comment by TheLimePixel** [comment]
Tank don't work like buckets.
