### ISSUE TITLE
Quest order for Bees does not make sense

### ISSUE THREAD

**Issue by tjsd** [TheLimePixel/GregBlock#81]
Age 1 - The natural Age

When you create a bee attractor you give quests for Tropical Bees and Watery bees. Both of those cannot be used before you have gone into binnies genetics. Also as the quest stands now I am "stuck", I have no idea how to proceed with bees from this stage.

https://i.imgur.com/zM7hQWl.png

**Comment by TheLimePixel** [comment]
Not necessarily, if you have the corresponding biome nearby. Anyways, what you need to do is to make a Cutting Machine, then and engine and then a carpenter.
