### ISSUE TITLE
cannot assemble the Large Bronze Boiler

### ISSUE THREAD

**Issue by miezebieze** [TheLimePixel/GregBlock#83]
I made all the quest requirements but cannot figure out how to build the thing.

**Comment by TheLimePixel** [comment]
JEI.

**Comment by miezebieze** [comment]
Oh. Excuse me then.

I have found the multiblock tab once (when I built the blast furnace) but the tab doesn't have an icon and is nearly invisible if you don't know that it's there.
It didn't help at all that the recipe of the controller block takes a firebox casing as an ingredient and the page I found on the ftb wiki shows it as a part of the lowest level with all the other firebox casings...

Thanks for your quick response and the modpack in general. I'm enjoying it very much.
