### ISSUE TITLE
Steam can come out of the output side of the Steam Pump

### ISSUE THREAD

**Issue by adamcadot** [TheLimePixel/GregBlock#86]

**Comment by Radukan** [comment]
You've most likely ran out of water - hence the boiler outputted the steam in the "water" pipe. 
Boilers automatically output to any and every tank, drum, machine or pipe they can.

**Comment by TheLimePixel** [comment]
Good point, only pump water to the bottom of the boiler. Also according to the code for the pump, this happening is impossible.
