### ISSUE TITLE
Liquid Air to Argon Electrolyzer Recipe Missing

### ISSUE THREAD

**Issue by Numorphan** [TheLimePixel/GregBlock#89]
Version: 1.4.4
Server/Client: Server (but same problem in local)

The quest "Argon" says to freeze air in the vacuum freezer, and then put the liquid air into the electrolyzer to get Argon in some small quantity, but that electrolyzer recipe is missing. The only recipe I see for liquid air is in the mass fabricator (https://i.imgur.com/xsTaxQU.jpg). Attempting to put a bucket of liquid air directly into the electrolyzer using the GUI fails.

**Comment by TheLimePixel** [comment]
You use the cells.

**Comment by Numorphan** [comment]
No, that doesn't work either. To be clear, even if I fill a tank with liquid air and try to pipe it into the electrolyzer, it doesn't work. The electrolyzer is refusing to accept the fluid, as the recipe doesn't exist.

**Comment by TheLimePixel** [comment]
I'm saying that there's a recipe where you input a cell of liquid air as an item.

**Comment by Numorphan** [comment]
Ah, I see that. It might be good to mention using the cell in the quest, as everything else up to then involved the liquids directly, so I didn't go around looking for the cells (especially since basic fill/empty recipes using the cells are hidden in JEI, presumably to avoid clutter). It might also be good to add a reminder that you can fill/empty them with a fluid canner.
