### ISSUE TITLE
Q:  No receipe for Chalcopyrite Ore Chunk

### ISSUE THREAD

**Issue by demethan** [TheLimePixel/GregBlock#9]
I find Copper difficult to obtain compared to the other ores.  Seem the Chalcopyrite Ore Chunk doesn't give a recipe or stats.  Is this by design or was something missed?

Thanks .

**Comment by TheLimePixel** [comment]
:thinking: What do you mean?

**Comment by demethan** [comment]
lookup up Chalcopyrite Ore Chunk in the JEI, press R to find out how to get it. 

Nothing comes up.

**Comment by TheLimePixel** [comment]
No, there's a fine and a nether ore chunk. You see, with a String mesh, Copper is most easily obtainable.
