### ISSUE TITLE
Black sheep just randomly change color

### ISSUE THREAD

**Issue by FeedCat02** [TheLimePixel/GregBlock#93]
My sheep just change from black to either white or another color like red

**Comment by yarensc** [comment]
+1 happened after the restart after the update to 1.4.5 as well as randomly while playing a few hours in (after killing off the funny colors and re-breeding the heard of black sheep)

**Comment by adamcadot** [comment]
Will the sheep color be reverted in the next version or should we begin rebreeding the sheep?

**Comment by TheLimePixel** [comment]
The latter.
