### ISSUE TITLE
low voltage battery buffer doesn't output energy

### ISSUE THREAD

**Issue by Muphet** [TheLimePixel/GregBlock#94]
when using 9 slot battery buffer, first slot is not being used at all and power drain starts from slot 2 forward (slot 2 being first row and second column). additionally, it doesn't output fixed amount of amps like vanilla gt buffers do so using 9slot buffer with 9 batteries, 9 amps is being output every time (so 8x wires is not enough).

**Comment by TheLimePixel** [comment]
It outputs as many amps as there are batteries

**Comment by TheLimePixel** [comment]
Also, while I've seen the first battery not being used on streams, I haven't been able to reproduce it. I'm sure it will get used up at the end.
