### ISSUE TITLE
Battery Buffer Can't Output 2+ Amps to One Machine

### ISSUE THREAD

**Issue by Numorphan** [TheLimePixel/GregBlock#97]
Modpack Version: 1.4.6
Server/Client: Server

If you have a Battery Buffer as the output to your machines, and a single machine on the system needs a second amp to run properly, the Buffer will still only send a single amp, causing the machine to either run slowly or potentially not at all.

Example: Have an HV Battery Buffer filled with 16 Large Lithium Batteries, all fully charged. Have it send power over 4x Kanthal Cables to an HV Electrolyzer turning Water into Hydrogen/Oxygen, but have the distance be far enough so that you can't get 480 EU/tick in a single amp (mine was 20 cable lengths away).

What should happen: The Buffer occasionally sends a second amp, using 1 or 2 batteries depending on how many amps was sent that tick. One battery is constantly draining, the second drains less often.

What does happen: The Buffer always sends only one amp; the first battery is the only one losing energy. The Electrolyzer doesn't get all the power it asks for, and it runs slower while giving the lack of energy warning.

**Comment by TheLimePixel** [comment]
Well, it's specifically mentions on the tooltip that the Electrolyzer (and most machines in general) accepts only one amp, so out of all that power it's only going to receive 480EU/t.

**Comment by Numorphan** [comment]
When I removed the battery buffer, the machine was fully powered, in spite of it being further away from an output. Plus, I know most machines say they only input 1 amp, but then I wouldn't have been able to power my MV Precision Laser Engraver with several LV Turbines. So either basically every machine is bugged to allow for the input of several amps to make up for the eu/tick it needs, or the battery buffer is bugged in not being able to do that. I really hope it's the second, as if the first is the bug and it gets fixed, then that makes things DRAMATICALLY harder. You would be unable to pool lower tier resources together to get a single higher-tier machine to work, with the exception of something like the blast furnace. That would really suck.

Something is definitely bugged though.

**Comment by fluffle** [comment]
Don't run power through cables over long distances until you get to EV. Move steam, LPG or Cetane Diesel via pipes to local generators powering 3-5 machines via a 4A battery buffer. This minimises cable loss problems.

**Comment by Numorphan** [comment]
You aren't wrong, but the buffer is still inconsistent with how other outputs work.
