### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by ghost** [TheLimePixel/GregBlock#98]
Hello! I have a problem. After the mobfarm is built, hostile mobs do not spawn.

**Comment by programgames** [comment]
First of all , check that the platform is spawnable by setting the platform at Y like 52,53 ( not on slabs)...
And be sure that you are in a distance of ~ 32 blocks.
And then verify spawn ability with F7.
And wait, me and my friends waited a long time until mobs spawned.
